# Generated by Django 5.1.4 on 2025-03-02 13:40

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Berry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, editable=False, max_digits=6, verbose_name='Цена')),
                ('name', models.CharField(choices=[('blackberry', 'Ежевика'), ('raspberry', 'Малина'), ('blueberry', 'Голубика'), ('strawberry', 'Клубника')], max_length=50, unique=True, verbose_name='Ягоды')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Decor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, editable=False, max_digits=6, verbose_name='Цена')),
                ('name', models.CharField(choices=[('pistachios', 'фисташки '), ('meringue', 'безе'), ('hazelnut', 'фундук'), ('pecan', 'пекан'), ('marshmallow', 'маршмеллоу'), ('marzipan', 'марципан')], max_length=50, unique=True, verbose_name='Декор')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, editable=False, max_digits=6, verbose_name='Цена')),
                ('name', models.CharField(choices=[('1', '1 уровень'), ('2', '2 уровня'), ('3', '3 уровня')], max_length=50, unique=True, verbose_name='Уровень')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_orders', models.IntegerField(default=0, editable=False, verbose_name='Количество заказов')),
                ('total_sales', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Общий доход')),
                ('averange_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Средняя стоимость заказа')),
                ('last_order_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата последнего заказа')),
            ],
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, editable=False, max_digits=6, verbose_name='Цена')),
                ('name', models.CharField(choices=[('square', 'Квадрат'), ('circle', 'Круг'), ('rectangle', 'Прямоугольник')], max_length=50, unique=True, verbose_name='Форма торта')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, editable=False, max_digits=6, verbose_name='Цена')),
                ('name', models.CharField(choices=[('none', 'Без топпинга'), ('white_sauce', 'Белый соус'), ('caramel_syrup', 'Карамельный сироп'), ('maple_syrup', 'Кленовый сироп'), ('strawberry_syrup', 'Клубничный сироп'), ('blueberry_syrup', 'Черничный сироп'), ('milk_chocolate', 'Молочный шоколад')], max_length=50, unique=True, verbose_name='Топпинг')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='Номер телефона')),
            ],
        ),
        migrations.CreateModel(
            name='CustomCake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscription', models.CharField(blank=True, max_length=200, null=True, verbose_name='Надпись (+500 руб.)')),
                ('price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Цена')),
                ('berries', models.ManyToManyField(blank=True, to='bot.berry', verbose_name='Ягоды')),
                ('decor', models.ManyToManyField(blank=True, to='bot.decor', verbose_name='Декор')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.level', verbose_name='Уровень')),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.shape', verbose_name='Форма торта')),
                ('topping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.topping', verbose_name='Топинг')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StandardCake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscription', models.CharField(blank=True, max_length=200, null=True, verbose_name='Надпись (+500 руб.)')),
                ('price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Цена')),
                ('berries', models.ManyToManyField(blank=True, to='bot.berry', verbose_name='Ягоды')),
                ('decor', models.ManyToManyField(blank=True, to='bot.decor', verbose_name='Декор')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.level', verbose_name='Уровень')),
                ('shape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.shape', verbose_name='Форма торта')),
                ('topping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.topping', verbose_name='Топинг')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес доставки')),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата заказа')),
                ('delivery_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата доставки')),
                ('delivery_time', models.TimeField(verbose_name='Время доставки')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10, verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('custom_cake', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.customcake', verbose_name='Кастомный торт')),
                ('standard_cake', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.standardcake', verbose_name='Стандартный торт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.user', verbose_name='Заказчик')),
            ],
        ),
    ]
