# Generated by Django 5.1.4 on 2025-03-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_cakeorder_telegram_id_alter_cakeorder_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcake',
            name='topping',
            field=models.CharField(choices=[('chocolate', 'Шоколадный'), ('caramel', 'Карамельный'), ('berry', 'Ягодный'), ('none', 'Без топпинга')], max_length=20, verbose_name='Топпинг'),
        ),
    ]
