# Generated by Django 5.1.4 on 2025-03-04 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_cakeorder_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cakeorder',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='CustomCake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape', models.CharField(choices=[('round', 'Круглый'), ('square', 'Квадратный'), ('heart', 'Сердце')], max_length=20, verbose_name='Форма')),
                ('levels', models.IntegerField(choices=[(1, '1 уровень'), (2, '2 уровня'), (3, '3 уровня')], verbose_name='Уровни')),
                ('topping', models.CharField(choices=[('chocolate', 'Шоколадный'), ('caramel', 'Карамельный'), ('berry', 'Ягодный')], max_length=20, verbose_name='Топпинг')),
                ('berries', models.CharField(choices=[('strawberry', 'Клубника'), ('raspberry', 'Малина'), ('blueberry', 'Голубика'), ('none', 'Без ягод')], default='none', max_length=20, verbose_name='Ягоды')),
                ('decor', models.CharField(choices=[('nuts', 'Орехи'), ('cookies', 'Печенье'), ('marshmallow', 'Зефир'), ('none', 'Без декора')], default='none', max_length=20, verbose_name='Декор')),
                ('cake_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Надпись')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_cake', to='bot.cakeorder', verbose_name='Заказ')),
            ],
        ),
    ]
