# Generated by Django 5.1.4 on 2025-03-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_cakeorder_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcake',
            name='levels',
            field=models.IntegerField(choices=[(1, 'Первый уровень'), (2, 'Второй уровень'), (3, 'Третий уровень')], verbose_name='Уровни'),
        ),
        migrations.AlterField(
            model_name='customcake',
            name='topping',
            field=models.CharField(choices=[('chocolate', 'Шоколадный'), ('caramel', 'Карамельный'), ('berry', 'Ягодный')], max_length=20, verbose_name='Топпинг'),
        ),
    ]
