# Generated by Django 5.1.4 on 2025-03-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_alter_customcake_levels_alter_customcake_topping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcake',
            name='levels',
            field=models.IntegerField(choices=[('Один уровень', '1 уровень'), ('Два уровня', '2 уровня'), ('Три уровня', '3 уровня')], verbose_name='Уровни'),
        ),
    ]
