# Generated by Django 5.1.4 on 2025-03-05 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_alter_customcake_levels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customcake',
            name='order',
        ),
        migrations.AlterField(
            model_name='customcake',
            name='levels',
            field=models.IntegerField(choices=[(1, '1 уровень'), (2, '2 уровня'), (3, '3 уровня')], verbose_name='Уровни'),
        ),
        migrations.CreateModel(
            name='CustomCakeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('comment', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('telegram_id', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_cake', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_cake_order', to='bot.customcake')),
            ],
        ),
    ]
