# Generated by Django 5.1.4 on 2025-03-05 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_remove_customcake_order_alter_customcake_levels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcakeorder',
            name='custom_cake',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='bot.customcake'),
        ),
    ]
