# Generated by Django 5.1.4 on 2025-03-05 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_alter_customcakeorder_levels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcakeorder',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адресс'),
        ),
        migrations.AlterField(
            model_name='customcakeorder',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Пожелания'),
        ),
        migrations.AlterField(
            model_name='customcakeorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата оформления заказа'),
        ),
        migrations.AlterField(
            model_name='customcakeorder',
            name='custom_cake',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='bot.customcake', verbose_name='Кастомный торт'),
        ),
        migrations.AlterField(
            model_name='customcakeorder',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Стоимость'),
        ),
    ]
