# Generated by Django 5.1.4 on 2025-03-05 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_alter_customcakeorder_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customcakeorder',
            name='berries',
        ),
        migrations.RemoveField(
            model_name='customcakeorder',
            name='cake_text',
        ),
        migrations.RemoveField(
            model_name='customcakeorder',
            name='decor',
        ),
        migrations.RemoveField(
            model_name='customcakeorder',
            name='levels',
        ),
        migrations.RemoveField(
            model_name='customcakeorder',
            name='shape',
        ),
        migrations.RemoveField(
            model_name='customcakeorder',
            name='topping',
        ),
    ]
